### ISSUE TITLE
add instructions in README.md

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/GrapheneLab-Measurement-Code#45]

**Comment by Lrzivrnt** [comment]
download repository
unzip
copy folder to document
rename folder to GrapheneLab-Measurement-Code
install ancaconda and national instrument, Visa
open anaconda perompt, type the following
```
pip install pyvisa
```
```
pip install pyqtgraph
```
open another ancaconda perompt
type
```
jupyter notebook
```
open document/GrapheneLab-Measurement-Code/manual remote control/communitace with SRS830 LIA
run
